### ISSUE TITLE
[BUG_SP] Bunker Silo mode doesn't show up.

### ISSUE THREAD

**Issue by batuogkoc** [Courseplay/Courseplay_FS22#2322]
**READ FIRST**
https://github.com/Courseplay/Courseplay_FS22/wiki

**Steps to reproduce**
Hook a bunker silo leveler to any tractor

**Actual behavior**
When i attach a bunker silo leveler to a tractor, I can't see the "CP: Silo Work" option when i try to create a job. However, the mini-hud does display the option for the "wait in silo" or "wait in parking position". There is no other indication of the mode working. This happened with two different levelers, on all of the tractors I own (all stock). I tried disabling all other mods and extensions but the issue persisted

**Expected behavior**
For silo work mode to work.

**Screenshots**
![resim](https://user-images.githubusercontent.com/91716288/219126563-db94012c-262c-46a0-a6b2-4cf345c061aa.png)

**Courseplay version**
Version used: 7.2.0.2

**Log**
Please attach a log with all debug channels active.
For help with the debug channels,
please check out the readme at the github front page.
LOG:
https://gist.github.com/batuogkoc/fa3e83b24748a5bf5fad1eec7ab992c5

MAP:
https://gist.github.com/batuogkoc/3f6c5813f156487c5ff13e4daf48dfb7
You can test out the bug using the Valtra tractor or the Massey ferguson one near the large bunker silo.

**Map**
Map played on.
Elmcreek

**Vehicles/ implements involved**
Which vehicle or implement? Any tractor, any leveler.
Mod yes/no ? Not required to reproduce problem

**Relevant script mods**
Mods like Autodrive or VCA and so on.
Autodrive, Universal Autoloader. Although disabling them doesnt change the problem.

**Comment by Tensuko** [comment]
Can't open your log.
Wrong link?

**Comment by batuogkoc** [comment]
> Can't open your log. Wrong link?

Does it work now?

**Comment by Tensuko** [comment]
Fixed your links, but works just fine:

![fsScreen_2023_02_15_20_42_23](https://user-images.githubusercontent.com/27344744/219135983-70cc190d-bfc0-451c-a649-3dfe8e864c5a.png)
![fsScreen_2023_02_15_20_42_35](https://user-images.githubusercontent.com/27344744/219135999-364e59ae-fb77-4d67-b350-41e6a1db927b.png)

**Comment by Tensuko** [comment]
Toggle trough the start position (nearest waypoint) it should appear.
Strange is more that you get this HUD Screen with a shield attached.

Shield is normaly limited to Bunker Silo only.

**Comment by batuogkoc** [comment]
All i get when i click the nearest waypoint is the regular three options for it (nearest, first, last waypoint). It doesnt switch to bunkersilo mode. The problem is I cant set it up on the Create Job menu either. I only get GoTo.
![resim](https://user-images.githubusercontent.com/91716288/219138066-ca90e943-88ab-4819-8f9d-04978704afd6.png)

**Comment by Tensuko** [comment]
You dont even habe mods where I think it could cause Issues hmm.
Just try to remove that super person.
But I will try your tractor tmr.
Wich one is it exactly?

**Comment by batuogkoc** [comment]
I removed all mods (disabled all addons, expansion packs and deleted all mods from the mods folder other than courseplay) and it still doesn't work. No tractor that I own (MF 4708 M, Valtra 8750, JCB Fastrac 8330, NH T8.350 Genesis, Claas Arion 630) works. Doesnt matter if i attach the leveler to the front or back. I tried both the MSS 3700 and MES 500 levelers and neither of them work. In fact I tried this with CP 7.2.0.0 and some other older version (7.1.x.x but i dont remember it precisely) and it didn't work back then. In fact have never gotten any other result using CP Bunker silo mode in my life. In my original post I had added my map file. Could you maybe check that? I can provide you with other files/pictures/videos if they will be necessary.

**Comment by Tensuko** [comment]
Try to remove cp from mods, load save, save it, load it again with cp and also check modSettings folder, there is a cp folder wich contains course and fieldborder folder but also a config xml file, delete that file and try again

**Comment by batuogkoc** [comment]
I did what you said, removed cp from mods and the courseplay.xml file, launched my save and saved it. Then reinstalled cp and readded the courseplay.xml file. That fixed it. Thank you.

**Comment by batuogkoc** [comment]
I discovered what caused the bug. When I have a course loaded for my tractor this problem occurs. When I go and remove the course it fixes itself.

**Comment by Tensuko** [comment]
Then it is not a bug.
Remove the course and its good.
